[package]
name = "TypeTheorySamples"
version = "1.0.0"
authors = ["Rowan Goemans <r.goemans@student.science.ru.nl>", "Stefan Schrijvers <...>"]
edition = "2018"

[dependencies]

[[bin]]
name = "channels"
path = "src/channels.rs"

[[bin]]
name = "borrowing"
path = "src/borrowing.rs"
